[project]
name = "materia"
version = "0.1.0"
description = ""
authors = [
    {name = "L-Nafaryus", email = "l.nafaryus@gmail.com"},
]
dependencies = []
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false 

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/materia-server",
    "-e file:///${PROJECT_ROOT}/materia-web-client",
    "-e file:///${PROJECT_ROOT}/materia-client",
]
