docs_dir: src
site_dir: target/materia_docs

site_name: Materia Documentation
site_description: Materia cloud storage
#site_url:
repo_name: L-Nafaryus/materia 
repo_url: https://vcs.elnafo.ru/L-Nafaryus/materia
copyright: Copyright &copy; 2024 L-Nafaryus

theme:
  name: material
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: slate
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: default
    primary: deep purple
    accent: deep purple
    toggle:
      icon: material/weather-night
      name: Switch to dark mode


plugins:
- search:
- mkdocstrings:
    handlers:
      python:
        paths: [../server/src]  # search packages in the src folder
        options:
          extensions:
          - griffe_typingdoc
          #preload_modules:
          #- sqlalchemy
          #docstring_style: sphinx
          show_submodules: true
          show_source: true
          show_if_no_docstring: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_heading: true
          unwrap_annotated: true
          merge_init_into_class: true
          docstring_section_style: spacy
          signature_crossrefs: true
          inherited_members: true
          members_order: source
          separate_signature: true
          filters:
          - '!^_'

markdown_extensions:
  # Python Markdown
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  # Python Markdown Extensions
  pymdownx.betterem:
    smart_enable: all
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  # pymdownx blocks
  pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    # Custom types
    - info
    - check
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True

nav:
  - Usage: 
    - Introduction: index.md
    - usage/getting-started.md
  - Reference: 
    - reference/index.md
    - reference/app.md
    - reference/core.md
    - reference/models.md
    - reference/routers.md
    - reference/security.md
    - reference/tasks.md
  - Development:
    - devel/contrib.md 
    - devel/local.md
  - API: api.md
