"""empty message

Revision ID: 86dd738cbd40
Revises: 939b37d98be0
Create Date: 2024-07-05 16:42:31.645410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86dd738cbd40'
down_revision: Union[str, None] = '939b37d98be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_parent_id_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'directory', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('repository_user_id_fkey', 'repository', type_='foreignkey')
    op.create_foreign_key(None, 'repository', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repository', type_='foreignkey')
    op.create_foreign_key('repository_user_id_fkey', 'repository', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_parent_id_fkey', 'file', 'directory', ['parent_id'], ['id'])
    # ### end Alembic commands ###
